import { CinemaRoom } from "./interfaces/cinemarooms.interface.ts";
import { Movie, MovieGenre, MovieStatus, MovieVersion } from "./interfaces/movies.interface.ts";

// Mock data for genres
export const genresMockData: MovieGenre[] = [
  { id: "1", name: "Action" },
  { id: "2", name: "Comedy" },
  { id: "3", name: "Drama" },
  { id: "4", name: "Horror" },
  { id: "5", name: "Sci-Fi" },
  { id: "6", name: "Thriller" },
  { id: "7", name: "Romance" },
  { id: "8", name: "Fantasy" },
  { id: "9", name: "Crime" },
];

// Mock data for cinema rooms
export const cinemaRoomsMockData: CinemaRoom[] = [
  { id: "1", roomNumber: 101, type: "Standard", fee: 50000, capacity: 100, status: "ACTIVE", width: 10, length: 10 },
  { id: "2", roomNumber: 102, type: "VIP", fee: 80000, capacity: 80, status: "ACTIVE", width: 8, length: 10 },
  { id: "3", roomNumber: 103, type: "Premium", fee: 100000, capacity: 60, status: "MAINTENANCE", width: 8, length: 8 },
  { id: "4", roomNumber: 104, type: "Standard", fee: 50000, capacity: 100, status: "CLOSED", width: 10, length: 10 },
  { id: "5", roomNumber: 105, type: "VIP", fee: 120000, capacity: 40, status: "ACTIVE", width: 8, length: 8 },
];

export const moviesMockData: Movie[] = [
  {
    id: "1",
    title: "Avatar: The Way of Water",
    genre: "Action",
    genres: [
      { id: "1", name: "Action" },
      { id: "5", name: "Sci-Fi" },
      { id: "8", name: "Fantasy" },
    ],
    director: "James Cameron",
    actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Kate Winslet",
    releaseYear: 2022,
    startShowingDate: "2025-06-01",
    endShowingDate: "2025-08-01",
    productionCompany: "20th Century Studios",
    duration: 192,
    rating: 8.1,
    description:
      "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=d9MyW72ELq0",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.THREE_D,
    showtimes: [
      {
        id: "1",
        movieId: "1",
        cinemaRoomId: "4",
        date: "2025-06-16",
        startTime: "2025-06-16T10:00:00Z",
        endTime: "2025-06-16T13:12:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "2",
        movieId: "1",
        cinemaRoomId: "5",
        date: "2025-06-16",
        startTime: "2025-06-16T14:30:00Z",
        endTime: "2025-06-16T17:42:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
      {
        id: "3",
        movieId: "1",
        cinemaRoomId: "4",
        date: "2025-06-16",
        startTime: "2025-06-16T19:00:00Z",
        endTime: "2025-06-16T22:12:00Z",
        format: "3D Phụ đề",
        availableSeats: 45,
        price: 120000,
      },
    ],
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2025-06-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Top Gun: Maverick",
    genre: "Action",
    genres: [
      { id: "1", name: "Action" },
      { id: "3", name: "Drama" },
    ],
    director: "Joseph Kosinski",
    actors: "Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm",
    releaseYear: 2022,
    startShowingDate: "2025-06-01",
    endShowingDate: "2025-07-15",
    productionCompany: "Paramount Pictures",
    duration: 131,
    rating: 8.7,
    description:
      "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=qSqVVswa420",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.IMAX,
    showtimes: [
      {
        id: "4",
        movieId: "2",
        cinemaRoomId: "1",
        date: "2025-06-16",
        startTime: "2025-06-16T11:00:00Z",
        endTime: "2025-06-16T13:11:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "5",
        movieId: "2",
        cinemaRoomId: "2",
        date: "2025-06-16",
        startTime: "2025-06-16T15:00:00Z",
        endTime: "2025-06-16T17:11:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
      {
        id: "6",
        movieId: "2",
        cinemaRoomId: "3",
        date: "2025-06-16",
        startTime: "2025-06-16T20:00:00Z",
        endTime: "2025-06-16T22:11:00Z",
        format: "3D Phụ đề",
        availableSeats: 45,
        price: 120000,
      },
    ],
    createdAt: "2025-06-01T11:00:00Z",
    updatedAt: "2025-06-15T11:00:00Z",
  },
  {
    id: "3",
    title: "Dune: Part Two",
    genre: "Sci-Fi",
    genres: [
      { id: "5", name: "Sci-Fi" },
      { id: "1", name: "Action" },
      { id: "3", name: "Drama" },
    ],
    director: "Denis Villeneuve",
    actors: "Timothée Chalamet, Zendaya, Rebecca Ferguson, Oscar Isaac",
    releaseYear: 2024,
    startShowingDate: "2025-06-10",
    endShowingDate: "2025-08-10",
    productionCompany: "Warner Bros. Pictures",
    duration: 166,
    rating: 8.8,
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he must prevent a terrible future only he can foresee.",
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=Way9Dexny3w",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.IMAX,
    showtimes: [
      {
        id: "7",
        movieId: "3",
        cinemaRoomId: "4",
        date: "2025-06-16",
        startTime: "2025-06-16T13:30:00Z",
        endTime: "2025-06-16T16:16:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "8",
        movieId: "3",
        cinemaRoomId: "5",
        date: "2025-06-16",
        startTime: "2025-06-16T18:00:00Z",
        endTime: "2025-06-16T20:46:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
    ],
    createdAt: "2025-06-10T12:00:00Z",
    updatedAt: "2025-06-15T12:00:00Z",
  },
  {
    id: "4",
    title: "Spider-Man: No Way Home",
    genre: "Action",
    genres: [
      { id: "1", name: "Action" },
      { id: "5", name: "Sci-Fi" },
      { id: "8", name: "Fantasy" },
    ],
    director: "Jon Watts",
    actors: "Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon",
    releaseYear: 2021,
    startShowingDate: "2025-06-05",
    endShowingDate: "2025-07-20",
    productionCompany: "Sony Pictures Entertainment",
    duration: 148,
    rating: 8.4,
    description:
      "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.THREE_D,
    showtimes: [
      {
        id: "9",
        movieId: "4",
        cinemaRoomId: "1",
        date: "2025-06-16",
        startTime: "2025-06-16T16:00:00Z",
        endTime: "2025-06-16T18:28:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "10",
        movieId: "4",
        cinemaRoomId: "2",
        date: "2025-06-16",
        startTime: "2025-06-16T19:30:00Z",
        endTime: "2025-06-16T21:58:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
    ],
    createdAt: "2025-06-05T13:00:00Z",
    updatedAt: "2025-06-15T13:00:00Z",
  },
  {
    id: "5",
    title: "The Batman",
    genre: "Action",
    genres: [
      { id: "1", name: "Action" },
      { id: "9", name: "Crime" },
      { id: "6", name: "Thriller" },
    ],
    director: "Matt Reeves",
    actors: "Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright",
    releaseYear: 2022,
    startShowingDate: "2025-06-08",
    endShowingDate: "2025-07-25",
    productionCompany: "Warner Bros. Pictures",
    duration: 176,
    rating: 8.2,
    description:
      "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    poster: "https://image.tmdb.org/t/p/w500/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.IMAX,
    showtimes: [
      {
        id: "11",
        movieId: "5",
        cinemaRoomId: "3",
        date: "2025-06-16",
        startTime: "2025-06-16T12:00:00Z",
        endTime: "2025-06-16T14:56:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "12",
        movieId: "5",
        cinemaRoomId: "4",
        date: "2025-06-16",
        startTime: "2025-06-16T17:00:00Z",
        endTime: "2025-06-16T19:56:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
    ],
    createdAt: "2025-06-08T14:00:00Z",
    updatedAt: "2025-06-15T14:00:00Z",
  },
  {
    id: "6",
    title: "Black Panther: Wakanda Forever",
    genre: "Action",
    genres: [
      { id: "1", name: "Action" },
      { id: "5", name: "Sci-Fi" },
      { id: "3", name: "Drama" },
    ],
    director: "Ryan Coogler",
    actors: "Letitia Wright, Angela Bassett, Tenoch Huerta, Danai Gurira",
    releaseYear: 2022,
    startShowingDate: "2025-06-12",
    endShowingDate: "2025-08-05",
    productionCompany: "Marvel Studios",
    duration: 161,
    rating: 7.3,
    description: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    poster: "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=_Z3QKkl1WyM",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.FOUR_DX,
    showtimes: [
      {
        id: "13",
        movieId: "6",
        cinemaRoomId: "5",
        date: "2025-06-16",
        startTime: "2025-06-16T14:00:00Z",
        endTime: "2025-06-16T16:41:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "14",
        movieId: "6",
        cinemaRoomId: "1",
        date: "2025-06-16",
        startTime: "2025-06-16T21:00:00Z",
        endTime: "2025-06-16T23:41:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
    ],
    createdAt: "2025-06-12T15:00:00Z",
    updatedAt: "2025-06-15T15:00:00Z",
  },
  {
    id: "7",
    title: "Doctor Strange in the Multiverse of Madness",
    genre: "Action",
    genres: [
      { id: "1", name: "Action" },
      { id: "5", name: "Sci-Fi" },
      { id: "8", name: "Fantasy" },
      { id: "4", name: "Horror" },
    ],
    director: "Sam Raimi",
    actors: "Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor, Benedict Wong",
    releaseYear: 2022,
    startShowingDate: "2025-06-15",
    endShowingDate: "2025-07-30",
    productionCompany: "Marvel Studios",
    duration: 126,
    rating: 7.0,
    description:
      "Doctor Strange teams up with a mysterious young teenager who has the ability to travel across multiverses, to battle other-universe versions of himself and threaten to wipe out millions across the multiverse.",
    poster: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=aWzlQ2N6qqg",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.THREE_D,
    showtimes: [
      {
        id: "15",
        movieId: "7",
        cinemaRoomId: "2",
        date: "2025-06-16",
        startTime: "2025-06-16T10:30:00Z",
        endTime: "2025-06-16T12:36:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "16",
        movieId: "7",
        cinemaRoomId: "3",
        date: "2025-06-16",
        startTime: "2025-06-16T18:30:00Z",
        endTime: "2025-06-16T20:36:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
    ],
    createdAt: "2025-06-15T16:00:00Z",
    updatedAt: "2025-06-15T16:00:00Z",
  },
  {
    id: "8",
    title: "Jurassic World Dominion",
    genre: "Action",
    genres: [
      { id: "1", name: "Action" },
      { id: "5", name: "Sci-Fi" },
      { id: "6", name: "Thriller" },
    ],
    director: "Colin Trevorrow",
    actors: "Chris Pratt, Bryce Dallas Howard, Laura Dern, Sam Neill",
    releaseYear: 2022,
    startShowingDate: "2025-06-01",
    endShowingDate: "2025-07-15",
    productionCompany: "Universal Pictures",
    duration: 147,
    rating: 5.6,
    description:
      "Four years after the destruction of Isla Nublar, dinosaurs now live and hunt alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history's most fearsome creatures.",
    poster: "https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=fb5ELWi-ekk",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.FOUR_DX,
    showtimes: [
      {
        id: "17",
        movieId: "8",
        cinemaRoomId: "1",
        date: "2025-06-16",
        startTime: "2025-06-16T13:00:00Z",
        endTime: "2025-06-16T15:27:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "18",
        movieId: "8",
        cinemaRoomId: "4",
        date: "2025-06-16",
        startTime: "2025-06-16T20:30:00Z",
        endTime: "2025-06-16T22:57:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
    ],
    createdAt: "2025-06-01T17:00:00Z",
    updatedAt: "2025-06-15T17:00:00Z",
  },
  {
    id: "9",
    title: "Minions: The Rise of Gru",
    genre: "Comedy",
    genres: [
      { id: "2", name: "Comedy" },
      { id: "8", name: "Fantasy" },
    ],
    director: "Kyle Balda",
    actors: "Steve Carell, Pierre Coffin, Alan Arkin, Taraji P. Henson",
    releaseYear: 2022,
    startShowingDate: "2025-06-05",
    endShowingDate: "2025-08-20",
    productionCompany: "Universal Pictures",
    duration: 87,
    rating: 6.5,
    description: "The untold story of one twelve-year-old's dream to become the world's greatest supervillain.",
    poster: "https://image.tmdb.org/t/p/w500/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=BUIgZd8w2yc",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.TWO_D,
    showtimes: [
      {
        id: "19",
        movieId: "9",
        cinemaRoomId: "2",
        date: "2025-06-16",
        startTime: "2025-06-16T09:00:00Z",
        endTime: "2025-06-16T10:27:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
    ],
    createdAt: "2025-06-05T18:00:00Z",
    updatedAt: "2025-06-15T18:00:00Z",
  },
  {
    id: "10",
    title: "Lightyear",
    genre: "Animation",
    genres: [
      { id: "2", name: "Comedy" },
      { id: "5", name: "Sci-Fi" },
      { id: "8", name: "Fantasy" },
    ],
    director: "Angus MacLane",
    actors: "Chris Evans, Keke Palmer, Peter Sohn, Taika Waititi",
    releaseYear: 2022,
    startShowingDate: "2025-06-08",
    endShowingDate: "2025-08-15",
    productionCompany: "Pixar Animation Studios",
    duration: 105,
    rating: 6.1,
    description: "The story of Buzz Lightyear and his adventures to infinity and beyond.",
    poster: "https://image.tmdb.org/t/p/w500/ox4goZd956BxqJH6iLwhWPL9ct4.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=BwPL0Md_QFQ",
    status: MovieStatus.ACTIVE,
    version: MovieVersion.THREE_D,
    showtimes: [
      {
        id: "22",
        movieId: "10",
        cinemaRoomId: "1",
        date: "2025-06-16",
        startTime: "2025-06-16T08:30:00Z",
        endTime: "2025-06-16T10:15:00Z",
        format: "3D Phụ đề",
        availableSeats: 50,
        price: 120000,
      },
      {
        id: "23",
        movieId: "10",
        cinemaRoomId: "4",
        date: "2025-06-16",
        startTime: "2025-06-16T15:00:00Z",
        endTime: "2025-06-16T16:45:00Z",
        format: "3D Phụ đề",
        availableSeats: 30,
        price: 150000,
      },
    ],
    createdAt: "2025-06-08T19:00:00Z",
    updatedAt: "2025-06-15T19:00:00Z",
  },
];

// CRUD Operations
export const moviesAPI = {
  getAll: () => moviesMockData,

  getById: (id: string) => moviesMockData.find((movie) => movie.id === id),

  create: (movieData: Omit<Movie, "id" | "createdAt" | "updatedAt">) => {
    const newMovie: Movie = {
      ...movieData,
      id: (moviesMockData.length + 1).toString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    moviesMockData.push(newMovie);
    return newMovie;
  },

  update: (id: string, movieData: Partial<Omit<Movie, "id" | "createdAt">>) => {
    const index = moviesMockData.findIndex((movie) => movie.id === id);
    if (index !== -1) {
      moviesMockData[index] = {
        ...moviesMockData[index],
        ...movieData,
        updatedAt: new Date().toISOString(),
      };
      return moviesMockData[index];
    }
    return null;
  },

  delete: (id: string) => {
    const index = moviesMockData.findIndex((movie) => movie.id === id);
    if (index !== -1) {
      const deletedMovie = moviesMockData.splice(index, 1)[0];
      return deletedMovie;
    }
    return null;
  },
};

// API for genres
export const genresAPI = {
  getAll: () => genresMockData,
  getById: (id: string) => genresMockData.find((genre) => genre.id === id),
};

// API for cinema rooms
export const cinemaRoomsAPI = {
  getAll: () => cinemaRoomsMockData,
  getById: (id: string) => cinemaRoomsMockData.find((room) => room.id === id),
};
