import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../../schema-from-be"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: `${import.meta.env.VITE_API_URL}/movie_theater/`,
  headers: {
    "Content-Type": "application/json",
  },
});
export const $api = createClient(fetchClient);
